services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ecommerce_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-ecommerce_db}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
#  app:
#    build: .
#    container_name: e_commerce_app
#    ports:
#      - "8080:8080"
#    environment:
#      # Override application.properties to connect to the 'db' service
#     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommerce_db
#      SPRING_DATASOURCE_USERNAME: ecommerce_user
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_PROFILES_ACTIVE: prod
#    depends_on:
#      db:
#        condition: service_healthy
#    restart: always # Always restart if the container stops unexpectedly
volumes:
  db-data: